{
  branches: [
    {
      name: 'master'
    },
    {
      name: 'pre/rc', 
      channel: 'pre/rc', 
      prerelease: 'rc'
    },
    {
      name: 'beta', 
      channel: 'beta', 
      prerelease: 'beta'
    }
  ],
  plugins: [
    "@semantic-release/gitlab",
    "@semantic-release/commit-analyzer", {
      releaseRules: [
        {breaking: true, release: 'major'},
        {revert: true, release: 'patch'},
        {type: 'feat', release: 'minor'},
        {type: 'fix', release: 'patch'},
        {type: 'perf', release: 'patch'},
        {emoji: ':racehorse:', release: 'patch'},
        {emoji: ':bug:', release: 'patch'},
        {emoji: ':penguin:', release: 'patch'},
        {emoji: ':apple:', release: 'patch'},
        {emoji: ':checkered_flag:', release: 'patch'},
        {tag: 'BUGFIX', release: 'patch'},
        {tag: 'FEATURE', release: 'minor'},
        {tag: 'SECURITY', release: 'patch'},
        {tag: 'Breaking', release: 'major'},
        {tag: 'breaking', release: 'major'},
        {tag: 'Fix', release: 'patch'},
        {tag: 'Update', release: 'minor'},
        {tag: 'New', release: 'minor'},
        {component: 'perf', release: 'patch'},
        {component: 'deps', release: 'patch'},
        {type: 'FEAT', release: 'minor'},
        {type: 'FIX', release: 'patch'},
        {type: "docs", release: "patch"},
        {type: "refactor", release: "patch"},
        {type: "style", release: "patch"}
      ],
      parserOpts: {
        noteKeywords: [
          "BREAKING CHANGE",
          "BREAKING CHANGES"
        ]
      }
    },
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    [
      "@semantic-release/changelog",
      {
        changelogFile: "CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/git",
      {
        assets: ["CHANGELOG.md"]
      }
    ]
  ]
}